services:

  postgres:
    image: postgres:15
    container_name: treasury_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mavi123
      POSTGRES_DB: US_Treasury
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow-db:
    image: postgres:15
    container_name: airflow_postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow_db_data:/var/lib/postgresql/data

  airflow:
    image: apache/airflow:2.9.1
    container_name: airflow
    depends_on:
      - airflow-db
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      PYTHONPATH: /opt/airflow/app
    volumes:
      - ./dags:/opt/airflow/dags
      - .:/opt/airflow/app
    ports:
      - "8088:8088"
    command: >
      bash -c "
      sleep 10 &&
      airflow db init &&
      airflow users create
      --username admin
      --password admin
      --firstname Moavia
      --lastname Mahmood
      --role Admin
      --email admin@example.com &&
      airflow webserver & airflow scheduler
      "


  spark:
    image: apache/spark:3.5.1
    container_name: spark
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "7077:7077"
      - "8081:8080"
    volumes:
      - ./data:/data
      - ./raw_data:/opt/airflow/app/raw_data
      - .:/opt/spark-apps

volumes:
  postgres_data:
  airflow_db_data:
